version: '3'

services:
  prisma:
    network_mode: "host"
    depends_on:
      - mysql
    restart: always
    build:
      dockerfile: ../node_modules/@etidbury/ts-gql-helpers/prisma/Dockerfile
      context: ./prisma
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET}
    ports:
    - "4466:4466"
    # environment:
    #   - MYSQL_DATABASE='db-local'
    #   - MYSQL_HOST='localhost'
    #   - MYSQL_USER='root'
    #   - MYSQL_PASSWORD=''
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
